---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos-7
    image: localhost/systemd:centos-7
    command: /usr/sbin/init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-8
    image: localhost/systemd:centos-8
    command: /usr/sbin/init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-10
    image: localhost/systemd-python:debian-10
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-11
    image: localhost/systemd-python3:debian-11
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora-34
    image: localhost/systemd:fedora-34
    command: /usr/sbin/init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-focal
    image: localhost/systemd:ubuntu-focal
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-hirsute
    image: localhost/systemd:ubuntu-hirsute
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
 
provisioner:
  name: ansible
verifier:
  name: ansible
