---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos-7
    image: localhost/systemd:centos-7
    command: /usr/sbin/init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-8
    image: localhost/systemd:centos-8
    command: /usr/sbin/init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian
    image: docker.io/pycontribs/debian
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
